version: '3.9'
services:
  # MongoDB service
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
  
  # Node API service
  api:
    build: .
    ports:
      - 4400:4400
    environment:
      PORT: 4400
      MONGO_DB_URL: mongodb://mongo_db:27017
      DB_NAME: recipe
      NAME: RECIPE_APP
      ACCESS_TOKEN_SECRET: 123456
      REFRESH_TOKEN_SECRET: 123456
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}